version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  identity.api:
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApplicationName=Identity.API
      - ApplicationUri=http://localhost:13712
      - MvcClient=http://localhost:4398
      - BasketApiClient=http://basket.api
    ports:
      - "13712:80"


  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ordering.backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  recommendation.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  usermanagement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ibookstoremvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://10.0.75.1:13712
      - ApiGatewayUrl=http://apigateway
      - CallbackUrl=http://ibookstoremvc
    ports:
      - "4398:80"


  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

