version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - "rabbitmq"
      - "apigateway"


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - "rabbitmq"
      - "apigateway"
      - identity.api

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    ports:
      - "13712:80"
    depends_on:
      - "rabbitmq"
      - "apigateway"


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - "rabbitmq"
      - "apigateway"


  ordering.backgroundtasks:
    image: ${DOCKER_REGISTRY-}orderingbackgroundtasks
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - "rabbitmq"
      - "apigateway"


  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - "rabbitmq"
      - "apigateway"


  recommendation.api:
    image: ${DOCKER_REGISTRY-}recommendationapi
    build:
      context: .
      dockerfile: Services/Recommendation/Recommendation.API/Dockerfile
    depends_on:
      - "rabbitmq"
      - "apigateway"


  usermanagement.api:
    image: ${DOCKER_REGISTRY-}usermanagementapi
    build:
      context: .
      dockerfile: Services/UserManagement/UserManagement.API/Dockerfile
    depends_on:
      - "rabbitmq"
      - "apigateway"


  ibookstoremvc:
    image: ${DOCKER_REGISTRY-}ibookstoremvc
    build:
      context: .
      dockerfile: Web/iBookStoreMVC/Dockerfile
    depends_on:
      - "rabbitmq"
      - "apigateway"


  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    depends_on:
      - "rabbitmq"


  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"